{{- $name := include "service.name" . }}

{{- if .Values.service.http.exposed }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  labels:
    {{- include "service.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: {{ .Values.service.http.port }}
  selector:
    {{- include "service.selectorLabels" . | nindent 4 }}
{{- end }}