apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: cluster-secret-store
spec:
  provider:
    fake:
      data:
      - key: "cart/db"
        valueMap:
          writerEndpoint: db
          readerEndpoint: db
          port: "3306"
          username: administrator
          password: welcome
      - key: "order/db"
        valueMap:
          writerEndpoint: db
          readerEndpoint: db
          port: "3306"
          username: administrator
          password: welcome
