apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: metrics-server
  repo: https://kubernetes-sigs.github.io/metrics-server/
  version: v3.10.0
  releaseName: metrics-server
  namespace: kube-system
  includeCRDs: true
  valuesFile: values.yaml