service:
  name: coffee
  http:
    port: 8080
    exposed: true

image:
  repository: coffee
  tag: latest
  pullPolicy: IfNotPresent

env:
- name: TZ
  value: UTC

resources:
  app:
    limits:
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 64Mi

deployment:
  kind: Deployment
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  # kind: Rollout
  # strategy:
  #   type: RollingUpdate
  #   rollingUpdate:
  #     maxSurge: 1
  #     maxUnavailable: 0
  #   canary:
  #     maxSurge: 1
  #     maxUnavailable: 0

autoscaling:
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage:
  targetMemoryUtilizationPercentage:

livenessProbe:
  enabled: true
  path: /
  initialDelaySeconds: 20

readinessProbe:
  enabled: true
  path: /
  initialDelaySeconds: 20

ingress:
  enabled: false
  annotations: {}
  hosts:
  - host: coffee.example.com
    paths:
    - path: /

secrets:
  db: []
