service:
  name: cart
  http:
    port: 8080
    exposed: true
image:
  repository: ghcr.io/peppydays/coffee/cart/api
  tag: latest
  pullPolicy: IfNotPresent
env:
  - name: TZ
    value: UTC
resources:
  app:
    limits:
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 64Mi
deployment:
  kind: Rollout
  strategy:
    canary:
      maxSurge: 1
      maxUnavailable: 0
      steps:
        - setCanaryScale:
            weight: 1
        - setWeight: 100
      # - pause: {}
autoscaling:
  minReplicas: 1
  maxReplicas: 1
livenessProbe:
  enabled: true
  path: /
  initialDelaySeconds: 5
readinessProbe:
  enabled: true
  path: /
  initialDelaySeconds: 5
ingress:
  enabled: true
  hosts:
    - host: cart.example.com
      paths:
        - path: /
secrets:
  db:
    - cart-db
