apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: order-db
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secret-store
  target:
    name: order-db
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        host: "{{ .writerEndpoint }}"
        port: "{{ .port }}"
        schema: order
        username: "{{ .username }}"
        password: "{{ .password }}"
  data:
  - secretKey: writerEndpoint
    remoteRef:
      property: writerEndpoint
      key: order/db
  - secretKey: readerEndpoint
    remoteRef:
      property: readerEndpoint
      key: order/db
  - secretKey: port
    remoteRef:
      property: port
      key: order/db
  - secretKey: username
    remoteRef:
      property: username
      key: order/db
  - secretKey: password
    remoteRef:
      property: password
      key: order/db